import type { Metadata } from 'next';
import { NTR } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ntr = NTR({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-ntr',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ntr.className}>{children}</body>
    </html>
  );
}
